In [1]:
# Add the Pandas dependency.
import pandas as pd

In [2]:
# File to load
vacation_cities = "WeatherPy_challenge.csv"

In [3]:
# Read the school data file and store it in a Pandas DataFrame.
vacation_cities_df = pd.read_csv(vacation_cities)
vacation_cities_df.head()

,Unnamed: 0,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
0,0,Pleasanton,US,2020-02-20 04:22:04,37.66,-121.87,55.40,53,90,6.93,overcast clouds,0.00,0.0
1,1,New Norfolk,AU,2020-02-20 04:25:10,-42.78,147.06,68.00,42,75,18.34,broken clouds,0.00,0.0
2,2,Castro,BR,2020-02-20 04:25:10,-24.79,-50.01,66.65,97,94,2.51,light rain,0.94,0.0
3,3,Hilo,US,2020-02-20 04:25:10,19.73,-155.09,73.40,73,75,8.05,broken clouds,0.00,0.0
4,4,Cape Town,ZA,2020-02-20 04:20:21,-33.93,18.42,69.01,100,75,17.22,broken clouds,0.00,0.0

In [4]:
vacation_cities_df = vacation_cities_df.drop(['Unnamed: 0'], axis = 1)
vacation_cities_df

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
0,Pleasanton,US,2020-02-20 04:22:04,37.66,-121.87,55.40,53,90,6.93,overcast clouds,0.00,0.0
1,New Norfolk,AU,2020-02-20 04:25:10,-42.78,147.06,68.00,42,75,18.34,broken clouds,0.00,0.0
2,Castro,BR,2020-02-20 04:25:10,-24.79,-50.01,66.65,97,94,2.51,light rain,0.94,0.0
3,Hilo,US,2020-02-20 04:25:10,19.73,-155.09,73.40,73,75,8.05,broken clouds,0.00,0.0
4,Cape Town,ZA,2020-02-20 04:20:21,-33.93,18.42,69.01,100,75,17.22,broken clouds,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
576,Porto Nacional,BR,2020-02-20 04:27:22,-10.71,-48.42,72.84,91,100,2.28,overcast clouds,0.00,0.0
577,Zaltan,LY,2020-02-20 04:27:22,32.95,11.87,55.33,78,46,7.40,scattered clouds,0.00,0.0
578,Atambua,ID,2020-02-20 04:27:22,-9.11,124.89,83.91,65,74,3.94,broken clouds,0.00,0.0
579,Homa Bay,KE,2020-02-20 04:27:23,-0.53,34.46,68.00,88,20,6.93,few clouds,0.00,0.0
580,Puerto Del Rosario,ES,2020-02-20 04:27:23,28.50,-13.86,62.60,67,75,17.22,broken clouds,0.00,0.0

In [5]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 100

In [6]:
# Filter the dataset to find the cities that fit the criteria.
vacation_cities_df = vacation_cities_df.loc[(vacation_cities_df["Max Temp"] <= max_temp) & \
                                       (vacation_cities_df["Max Temp"] >= min_temp)]
vacation_cities_df

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
6,Mahibadhoo,MV,2020-02-20 04:25:11,3.78,72.97,81.66,74,0,17.83,clear sky,0.00,0.0
11,Rikitea,PF,2020-02-20 04:25:12,-23.12,-134.97,78.62,79,21,13.11,few clouds,0.00,0.0
16,Busselton,AU,2020-02-20 04:25:13,-33.65,115.33,91.99,17,0,12.97,clear sky,0.00,0.0
18,Atuona,PF,2020-02-20 04:25:14,-9.80,-139.03,81.99,79,27,17.56,light rain,0.13,0.0
19,Padang,ID,2020-02-20 04:25:14,-0.95,100.35,79.05,61,43,7.72,scattered clouds,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
567,Benjamin Constant,BR,2020-02-20 04:27:20,-4.38,-70.03,78.80,100,40,0.31,scattered clouds,0.00,0.0
570,Epe,NG,2020-02-20 04:27:21,6.58,3.98,76.69,95,33,1.34,scattered clouds,0.00,0.0
572,Palu,ID,2020-02-20 04:27:21,-0.89,119.87,81.27,69,0,3.00,light rain,2.19,0.0
573,Caravelas,BR,2020-02-20 04:27:21,-17.71,-39.25,80.56,83,0,10.11,light rain,0.63,0.0
578,Atambua,ID,2020-02-20 04:27:22,-9.11,124.89,83.91,65,74,3.94,broken clouds,0.00,0.0

In [7]:
# Ask the customer to add a minimum and maximum temperature value.
rain_yes_no = str(input("Would you like rain during your trip (y or n)? "))
if rain_yes_no == "y":
    print("Thanks!")
    snow_yes_no = str(input("Would you like snow during your trip (y or n)? "))
    if snow_yes_no =="y":
        print("Thanks!")
    elif snow_yes_no =="n":
        print("Thanks!")
    else:
        print("Please start again and enter y or n.")

elif rain_yes_no == "n":
    snow_yes_no = str(input("Would you like snow during your trip (y or n)? "))
    if snow_yes_no =="y":
        print("Thanks!")
    elif snow_yes_no =="n":
        print("Thanks!")
    else:
        print("Please start again and enter y or n.")

else:
    print("Please start again and enter y or n.")

Would you like rain during your trip (y or n)? n
Would you like snow during your trip (y or n)? n
Thanks!

In [8]:
# Filter the dataset to find the cities that fit the criteria.

if rain_yes_no == "y":
    vacation_cities_df = vacation_cities_df.loc[(vacation_cities_df["Rain inches (last 3 hrs)"] > 0)]
    if snow_yes_no == "y":
        vacation_cities_df = vacation_cities_df.loc[(vacation_cities_df["Snow inches (last 3 hrs)"] > 0)]
    else:
        vacation_cities_df = vacation_cities_df.loc[(vacation_cities_df["Snow inches (last 3 hrs)"] == 0)]
    
else:
    rain_yes_no =="n"
    vacation_cities_df = vacation_cities_df.loc[(vacation_cities_df["Rain inches (last 3 hrs)"] == 0)]
    if snow_yes_no == "y":
        vacation_cities_df = vacation_cities_df.loc[(vacation_cities_df["Snow inches (last 3 hrs)"] > 0)]
    else:
        vacation_cities_df = vacation_cities_df.loc[(vacation_cities_df["Rain inches (last 3 hrs)"] == 0)]


vacation_cities_df

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
6,Mahibadhoo,MV,2020-02-20 04:25:11,3.78,72.97,81.66,74,0,17.83,clear sky,0.0,0.0
11,Rikitea,PF,2020-02-20 04:25:12,-23.12,-134.97,78.62,79,21,13.11,few clouds,0.0,0.0
16,Busselton,AU,2020-02-20 04:25:13,-33.65,115.33,91.99,17,0,12.97,clear sky,0.0,0.0
19,Padang,ID,2020-02-20 04:25:14,-0.95,100.35,79.05,61,43,7.72,scattered clouds,0.0,0.0
26,Kayes,ML,2020-02-20 04:25:16,14.00,-11.00,75.20,33,0,2.24,clear sky,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
562,Ahipara,NZ,2020-02-20 04:27:19,-35.17,173.17,82.99,73,93,1.01,overcast clouds,0.0,0.0
563,Port-Gentil,GA,2020-02-20 04:27:19,-0.72,8.78,80.29,84,100,11.01,overcast clouds,0.0,0.0
567,Benjamin Constant,BR,2020-02-20 04:27:20,-4.38,-70.03,78.80,100,40,0.31,scattered clouds,0.0,0.0
570,Epe,NG,2020-02-20 04:27:21,6.58,3.98,76.69,95,33,1.34,scattered clouds,0.0,0.0
578,Atambua,ID,2020-02-20 04:27:22,-9.11,124.89,83.91,65,74,3.94,broken clouds,0.0,0.0

In [9]:
vacation_cities_df.to_csv('WeatherPy_vacation.csv')

In [10]:
# Import dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [11]:
# Store the CSV you saved created in part one into a DataFrame.
challenge_cities_df = pd.read_csv("WeatherPy_vacation.csv")
challenge_cities_df.head()

,Unnamed: 0,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
0,6,Mahibadhoo,MV,2020-02-20 04:25:11,3.78,72.97,81.66,74,0,17.83,clear sky,0.0,0.0
1,11,Rikitea,PF,2020-02-20 04:25:12,-23.12,-134.97,78.62,79,21,13.11,few clouds,0.0,0.0
2,16,Busselton,AU,2020-02-20 04:25:13,-33.65,115.33,91.99,17,0,12.97,clear sky,0.0,0.0
3,19,Padang,ID,2020-02-20 04:25:14,-0.95,100.35,79.05,61,43,7.72,scattered clouds,0.0,0.0
4,26,Kayes,ML,2020-02-20 04:25:16,14.00,-11.00,75.20,33,0,2.24,clear sky,0.0,0.0

In [12]:
# Get the data types.
challenge_cities_df.dtypes

Unnamed: 0                    int64
City                         object
Country                      object
Date                         object
Lat                         float64
Lng                         float64
Max Temp                    float64
Humidity                      int64
Cloudiness                    int64
Wind Speed                  float64
Current Description          object
Rain inches (last 3 hrs)    float64
Snow inches (last 3 hrs)    float64
dtype: object

In [13]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [14]:
# Get the maximum temperature.
max_temp = challenge_cities_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [15]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = challenge_cities_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = challenge_cities_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=temps, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [16]:
# Heatmap of percent humidity
locations = challenge_cities_df[["Lat", "Lng"]]
humidity = challenge_cities_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [17]:
# Heatmap of percent cloudiness
locations = challenge_cities_df[["Lat", "Lng"]]
clouds = challenge_cities_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [18]:
# Heatmap of percent wind speed
locations = challenge_cities_df[["Lat", "Lng"]]
wind = challenge_cities_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [19]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = challenge_cities_df[["City", "Country", "Max Temp", "Current Description","Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Mahibadhoo,MV,81.66,clear sky,3.78,72.97,
1,Rikitea,PF,78.62,few clouds,-23.12,-134.97,
2,Busselton,AU,91.99,clear sky,-33.65,115.33,
3,Padang,ID,79.05,scattered clouds,-0.95,100.35,
4,Kayes,ML,75.20,clear sky,14.00,-11.00,
...,...,...,...,...,...,...,...
112,Ahipara,NZ,82.99,overcast clouds,-35.17,173.17,
113,Port-Gentil,GA,80.29,overcast clouds,-0.72,8.78,
114,Benjamin Constant,BR,78.80,scattered clouds,-4.38,-70.03,
115,Epe,NG,76.69,scattered clouds,6.58,3.98,
116,Atambua,ID,83.91,broken clouds,-9.11,124.89,

In [20]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [21]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [22]:
hotel_df = hotel_df
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Mahibadhoo,MV,81.66,clear sky,3.78,72.97,Omadhoo Inn
1,Rikitea,PF,78.62,few clouds,-23.12,-134.97,Pension Maro'i
2,Busselton,AU,91.99,clear sky,-33.65,115.33,Observatory Guest House
3,Padang,ID,79.05,scattered clouds,-0.95,100.35,Mercure Padang
4,Kayes,ML,75.20,clear sky,14.00,-11.00,
...,...,...,...,...,...,...,...
112,Ahipara,NZ,82.99,overcast clouds,-35.17,173.17,Ahipara Holiday Park
113,Port-Gentil,GA,80.29,overcast clouds,-0.72,8.78,Fengshui Residence
114,Benjamin Constant,BR,78.80,scattered clouds,-4.38,-70.03,CASA AVALIADA
115,Epe,NG,76.69,scattered clouds,6.58,3.98,MAGVILLE HOTEL
116,Atambua,ID,83.91,broken clouds,-9.11,124.89,Pondok Pesantren Al Muhajirin Atambua

In [23]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [24]:
# Add a marker for each city.
locations = hotel_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [25]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd>
</dl>
"""

In [26]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [27]:
# Add a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [28]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [29]:
# Store the CSV you saved created in part one into a DataFrame.
challenge_cities_df = pd.read_csv("WeatherPy_vacation.csv")
challenge_cities_df.head()

,Unnamed: 0,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
0,6,Mahibadhoo,MV,2020-02-20 04:25:11,3.78,72.97,81.66,74,0,17.83,clear sky,0.0,0.0
1,11,Rikitea,PF,2020-02-20 04:25:12,-23.12,-134.97,78.62,79,21,13.11,few clouds,0.0,0.0
2,16,Busselton,AU,2020-02-20 04:25:13,-33.65,115.33,91.99,17,0,12.97,clear sky,0.0,0.0
3,19,Padang,ID,2020-02-20 04:25:14,-0.95,100.35,79.05,61,43,7.72,scattered clouds,0.0,0.0
4,26,Kayes,ML,2020-02-20 04:25:16,14.00,-11.00,75.20,33,0,2.24,clear sky,0.0,0.0

In [30]:
# Get the data types.
challenge_cities_df.dtypes

Unnamed: 0                    int64
City                         object
Country                      object
Date                         object
Lat                         float64
Lng                         float64
Max Temp                    float64
Humidity                      int64
Cloudiness                    int64
Wind Speed                  float64
Current Description          object
Rain inches (last 3 hrs)    float64
Snow inches (last 3 hrs)    float64
dtype: object

In [31]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [32]:
# Get the maximum temperature.
max_temp = challenge_cities_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [33]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = challenge_cities_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = challenge_cities_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=temps, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [34]:
# Heatmap of percent humidity
locations = challenge_cities_df[["Lat", "Lng"]]
humidity = challenge_cities_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [35]:
# Heatmap of percent cloudiness
locations = challenge_cities_df[["Lat", "Lng"]]
clouds = challenge_cities_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [36]:
# Heatmap of percent wind speed
locations = challenge_cities_df[["Lat", "Lng"]]
wind = challenge_cities_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [37]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = challenge_cities_df[["City", "Country", "Max Temp", "Current Description","Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Mahibadhoo,MV,81.66,clear sky,3.78,72.97,
1,Rikitea,PF,78.62,few clouds,-23.12,-134.97,
2,Busselton,AU,91.99,clear sky,-33.65,115.33,
3,Padang,ID,79.05,scattered clouds,-0.95,100.35,
4,Kayes,ML,75.20,clear sky,14.00,-11.00,
...,...,...,...,...,...,...,...
112,Ahipara,NZ,82.99,overcast clouds,-35.17,173.17,
113,Port-Gentil,GA,80.29,overcast clouds,-0.72,8.78,
114,Benjamin Constant,BR,78.80,scattered clouds,-4.38,-70.03,
115,Epe,NG,76.69,scattered clouds,6.58,3.98,
116,Atambua,ID,83.91,broken clouds,-9.11,124.89,

In [38]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [39]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [40]:
hotel_df = hotel_df
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Mahibadhoo,MV,81.66,clear sky,3.78,72.97,Omadhoo Inn
1,Rikitea,PF,78.62,few clouds,-23.12,-134.97,Pension Maro'i
2,Busselton,AU,91.99,clear sky,-33.65,115.33,Observatory Guest House
3,Padang,ID,79.05,scattered clouds,-0.95,100.35,Mercure Padang
4,Kayes,ML,75.20,clear sky,14.00,-11.00,
...,...,...,...,...,...,...,...
112,Ahipara,NZ,82.99,overcast clouds,-35.17,173.17,Ahipara Holiday Park
113,Port-Gentil,GA,80.29,overcast clouds,-0.72,8.78,Fengshui Residence
114,Benjamin Constant,BR,78.80,scattered clouds,-4.38,-70.03,CASA AVALIADA
115,Epe,NG,76.69,scattered clouds,6.58,3.98,MAGVILLE HOTEL
116,Atambua,ID,83.91,broken clouds,-9.11,124.89,Pondok Pesantren Al Muhajirin Atambua

In [41]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [42]:
# Add a marker for each city.
locations = hotel_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [43]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd>
</dl>
"""

In [44]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [45]:
# Add a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))