In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
import gmaps.datasets
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
challenge_cities_df = pd.read_csv("WeatherPy_vacation.csv")
challenge_cities_df.head()

,Unnamed: 0,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
0,6,Mahibadhoo,MV,2020-02-20 04:25:11,3.78,72.97,81.66,74,0,17.83,clear sky,0.0,0.0
1,11,Rikitea,PF,2020-02-20 04:25:12,-23.12,-134.97,78.62,79,21,13.11,few clouds,0.0,0.0
2,16,Busselton,AU,2020-02-20 04:25:13,-33.65,115.33,91.99,17,0,12.97,clear sky,0.0,0.0
3,19,Padang,ID,2020-02-20 04:25:14,-0.95,100.35,79.05,61,43,7.72,scattered clouds,0.0,0.0
4,26,Kayes,ML,2020-02-20 04:25:16,14.00,-11.00,75.20,33,0,2.24,clear sky,0.0,0.0

In [3]:
aus_cities_df = challenge_cities_df.loc[(challenge_cities_df["Country"] == "AU")]
aus_cities_df

,Unnamed: 0,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
2,16,Busselton,AU,2020-02-20 04:25:13,-33.65,115.33,91.99,17,0,12.97,clear sky,0.0,0.0
24,116,Nambucca Heads,AU,2020-02-20 04:25:37,-30.65,153.00,82.00,54,0,11.41,clear sky,0.0,0.0
25,117,Esperance,AU,2020-02-20 04:25:38,-33.87,121.90,75.20,41,75,12.75,broken clouds,0.0,0.0
26,122,Port Hedland,AU,2020-02-20 04:25:39,-20.32,118.57,96.80,47,0,12.75,clear sky,0.0,0.0
28,131,Bundaberg,AU,2020-02-20 04:21:34,-24.85,152.35,93.20,52,40,3.36,scattered clouds,0.0,0.0
29,147,Geraldton,AU,2020-02-20 04:25:45,-28.77,114.60,80.60,61,90,11.41,overcast clouds,0.0,0.0
49,244,Alyangula,AU,2020-02-20 04:26:07,-13.85,136.42,82.40,83,40,5.82,scattered clouds,0.0,0.0
50,256,Sawtell,AU,2020-02-20 04:26:09,-30.38,153.10,82.00,54,0,11.41,clear sky,0.0,0.0
54,263,Carnarvon,AU,2020-02-20 04:26:11,-24.87,113.63,91.40,49,40,14.99,scattered clouds,0.0,0.0
61,302,Yulara,AU,2020-02-20 04:26:20,-25.24,130.99,93.20,16,98,10.29,overcast clouds,0.0,0.0
66,326,Alice Springs,AU,2020-02-20 04:23:32,-23.70,133.88,91.40,9,0,10.29,clear sky,0.0,0.0
72,339,Batemans Bay,AU,2020-02-20 04:26:28,-35.72,150.18,75.00,66,0,5.01,clear sky,0.0,0.0
89,442,Broken Hill,AU,2020-02-20 04:26:51,-31.95,141.43,75.20,27,89,11.41,overcast clouds,0.0,0.0
92,452,Yeppoon,AU,2020-02-20 04:26:53,-23.13,150.73,96.80,47,20,3.36,few clouds,0.0,0.0
93,453,Mount Isa,AU,2020-02-20 04:22:59,-20.73,139.50,96.80,19,0,9.17,clear sky,0.0,0.0
100,479,Byron Bay,AU,2020-02-20 04:22:43,-28.65,153.62,86.00,65,36,12.75,scattered clouds,0.0,0.0
111,559,Mackay,AU,2020-02-20 04:27:18,-21.15,149.20,91.99,70,16,12.75,few clouds,0.0,0.0

In [4]:
aus_cities_df = aus_cities_df.loc[(aus_cities_df["Lng"] > 149.1)]
aus_cities_df

,Unnamed: 0,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
24,116,Nambucca Heads,AU,2020-02-20 04:25:37,-30.65,153.00,82.00,54,0,11.41,clear sky,0.0,0.0
28,131,Bundaberg,AU,2020-02-20 04:21:34,-24.85,152.35,93.20,52,40,3.36,scattered clouds,0.0,0.0
50,256,Sawtell,AU,2020-02-20 04:26:09,-30.38,153.10,82.00,54,0,11.41,clear sky,0.0,0.0
72,339,Batemans Bay,AU,2020-02-20 04:26:28,-35.72,150.18,75.00,66,0,5.01,clear sky,0.0,0.0
92,452,Yeppoon,AU,2020-02-20 04:26:53,-23.13,150.73,96.80,47,20,3.36,few clouds,0.0,0.0
100,479,Byron Bay,AU,2020-02-20 04:22:43,-28.65,153.62,86.00,65,36,12.75,scattered clouds,0.0,0.0
111,559,Mackay,AU,2020-02-20 04:27:18,-21.15,149.20,91.99,70,16,12.75,few clouds,0.0,0.0

In [5]:
sorted_cities_df = aus_cities_df.sort_values(by='Lng', ascending=False)
sorted_cities_df

,Unnamed: 0,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
100,479,Byron Bay,AU,2020-02-20 04:22:43,-28.65,153.62,86.00,65,36,12.75,scattered clouds,0.0,0.0
50,256,Sawtell,AU,2020-02-20 04:26:09,-30.38,153.10,82.00,54,0,11.41,clear sky,0.0,0.0
24,116,Nambucca Heads,AU,2020-02-20 04:25:37,-30.65,153.00,82.00,54,0,11.41,clear sky,0.0,0.0
28,131,Bundaberg,AU,2020-02-20 04:21:34,-24.85,152.35,93.20,52,40,3.36,scattered clouds,0.0,0.0
92,452,Yeppoon,AU,2020-02-20 04:26:53,-23.13,150.73,96.80,47,20,3.36,few clouds,0.0,0.0
72,339,Batemans Bay,AU,2020-02-20 04:26:28,-35.72,150.18,75.00,66,0,5.01,clear sky,0.0,0.0
111,559,Mackay,AU,2020-02-20 04:27:18,-21.15,149.20,91.99,70,16,12.75,few clouds,0.0,0.0

In [6]:
sorted_cities_df = sorted_cities_df.reset_index(drop=True)
sorted_cities_df

,Unnamed: 0,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
0,479,Byron Bay,AU,2020-02-20 04:22:43,-28.65,153.62,86.00,65,36,12.75,scattered clouds,0.0,0.0
1,256,Sawtell,AU,2020-02-20 04:26:09,-30.38,153.10,82.00,54,0,11.41,clear sky,0.0,0.0
2,116,Nambucca Heads,AU,2020-02-20 04:25:37,-30.65,153.00,82.00,54,0,11.41,clear sky,0.0,0.0
3,131,Bundaberg,AU,2020-02-20 04:21:34,-24.85,152.35,93.20,52,40,3.36,scattered clouds,0.0,0.0
4,452,Yeppoon,AU,2020-02-20 04:26:53,-23.13,150.73,96.80,47,20,3.36,few clouds,0.0,0.0
5,339,Batemans Bay,AU,2020-02-20 04:26:28,-35.72,150.18,75.00,66,0,5.01,clear sky,0.0,0.0
6,559,Mackay,AU,2020-02-20 04:27:18,-21.15,149.20,91.99,70,16,12.75,few clouds,0.0,0.0

In [7]:
sorted_cities_df.drop(['Unnamed: 0'], axis=1)

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
0,Byron Bay,AU,2020-02-20 04:22:43,-28.65,153.62,86.00,65,36,12.75,scattered clouds,0.0,0.0
1,Sawtell,AU,2020-02-20 04:26:09,-30.38,153.10,82.00,54,0,11.41,clear sky,0.0,0.0
2,Nambucca Heads,AU,2020-02-20 04:25:37,-30.65,153.00,82.00,54,0,11.41,clear sky,0.0,0.0
3,Bundaberg,AU,2020-02-20 04:21:34,-24.85,152.35,93.20,52,40,3.36,scattered clouds,0.0,0.0
4,Yeppoon,AU,2020-02-20 04:26:53,-23.13,150.73,96.80,47,20,3.36,few clouds,0.0,0.0
5,Batemans Bay,AU,2020-02-20 04:26:28,-35.72,150.18,75.00,66,0,5.01,clear sky,0.0,0.0
6,Mackay,AU,2020-02-20 04:27:18,-21.15,149.20,91.99,70,16,12.75,few clouds,0.0,0.0

In [8]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = sorted_cities_df[["City", "Country", "Max Temp", "Current Description","Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Byron Bay,AU,86.00,scattered clouds,-28.65,153.62,
1,Sawtell,AU,82.00,clear sky,-30.38,153.10,
2,Nambucca Heads,AU,82.00,clear sky,-30.65,153.00,
3,Bundaberg,AU,93.20,scattered clouds,-24.85,152.35,
4,Yeppoon,AU,96.80,few clouds,-23.13,150.73,
5,Batemans Bay,AU,75.00,clear sky,-35.72,150.18,
6,Mackay,AU,91.99,few clouds,-21.15,149.20,

In [9]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [10]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

In [11]:
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Byron Bay,AU,86.00,scattered clouds,-28.65,153.62,Backpackers Inn on the Beach
1,Sawtell,AU,82.00,clear sky,-30.38,153.10,Boambee Waters Caravan Park
2,Nambucca Heads,AU,82.00,clear sky,-30.65,153.00,Marcel Towers Holiday Apartments
3,Bundaberg,AU,93.20,scattered clouds,-24.85,152.35,Takalvan Motel
4,Yeppoon,AU,96.80,few clouds,-23.13,150.73,Villa Mar Colina
5,Batemans Bay,AU,75.00,clear sky,-35.72,150.18,Coachhouse Marina Resort - Batemans Bay
6,Mackay,AU,91.99,few clouds,-21.15,149.20,International Lodge Motel

In [12]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [13]:
# Add a marker for each city.
locations = hotel_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(-30.0, 145.0), zoom_level=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [14]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp}&deg F</dd>
</dl>
"""

In [15]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [16]:
# Add a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(-30.0, 145.0), zoom_level=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [17]:
batemans_bay_df = hotel_df.loc[(hotel_df["City"] == "Batemans Bay")]
batemans_bay_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
5,Batemans Bay,AU,75.0,clear sky,-35.72,150.18,Coachhouse Marina Resort - Batemans Bay

In [18]:
subset = batemans_bay_df[['Lat', 'Lng']]
for x in subset.values:
    tuple(x)
    batemans_bay = tuple(x)
batemans_bay

(-35.72, 150.18)

In [19]:
nambucca_heads_df = hotel_df.loc[(hotel_df["City"] == "Nambucca Heads")]
nambucca_heads_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Nambucca Heads,AU,82.0,clear sky,-30.65,153.0,Marcel Towers Holiday Apartments

In [20]:
subset = nambucca_heads_df[['Lat', 'Lng']]
for x in subset.values:
    tuple(x)
    nambucca_heads = tuple(x)
nambucca_heads

(-30.65, 153.0)

In [21]:
sawtell_df = hotel_df.loc[(hotel_df["City"] == "Sawtell")]
sawtell_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Sawtell,AU,82.0,clear sky,-30.38,153.1,Boambee Waters Caravan Park

In [22]:
subset = sawtell_df[['Lat', 'Lng']]
for x in subset.values:
    tuple(x)
    sawtell = tuple(x)
sawtell

(-30.38, 153.1)

In [23]:
byron_bay_df = hotel_df.loc[(hotel_df["City"] == "Byron Bay")]
byron_bay_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Byron Bay,AU,86.0,scattered clouds,-28.65,153.62,Backpackers Inn on the Beach

In [24]:
subset = byron_bay_df[['Lat', 'Lng']]
for x in subset.values:
    tuple(x)
    byron_bay = tuple(x)
byron_bay

(-28.65, 153.62)

In [25]:
bundaberg_df = hotel_df.loc[(hotel_df["City"] == "Bundaberg")]
bundaberg_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Bundaberg,AU,93.2,scattered clouds,-24.85,152.35,Takalvan Motel

In [26]:
subset = bundaberg_df[['Lat', 'Lng']]
for x in subset.values:
    tuple(x)
    bundaberg = tuple(x)
bundaberg

(-24.85, 152.35)

In [27]:
yeppoon_df = hotel_df.loc[(hotel_df["City"] == "Yeppoon")]
yeppoon_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
4,Yeppoon,AU,96.8,few clouds,-23.13,150.73,Villa Mar Colina

In [28]:
subset = yeppoon_df[['Lat', 'Lng']]
for x in subset.values:
    tuple(x)
    yeppoon = tuple(x)
yeppoon

(-23.13, 150.73)

In [29]:
mackay_df = hotel_df.loc[(hotel_df["City"] == "Mackay")]
mackay_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
6,Mackay,AU,91.99,few clouds,-21.15,149.2,International Lodge Motel

In [30]:
subset = mackay_df[['Lat', 'Lng']]
for x in subset.values:
    tuple(x)
    mackay = tuple(x)
mackay

(-21.15, 149.2)

In [31]:
import gmaps
import gmaps.datasets

In [32]:
fig = gmaps.figure()

batemansbay_rt_via_stops = gmaps.directions_layer(
        batemans_bay, batemans_bay, waypoints=[nambucca_heads, sawtell, byron_bay, bundaberg, yeppoon, mackay],
        travel_mode='DRIVING') 
fig.add_layer(batemansbay_rt_via_stops)

fig

Figure(layout=FigureLayout(height='420px'))

In [33]:
itinerary_df = batemans_bay_df.append(nambucca_heads_df).append(sawtell_df).append(byron_bay_df).append(bundaberg_df).append(yeppoon_df).append(mackay_df)
itinerary_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
5,Batemans Bay,AU,75.00,clear sky,-35.72,150.18,Coachhouse Marina Resort - Batemans Bay
2,Nambucca Heads,AU,82.00,clear sky,-30.65,153.00,Marcel Towers Holiday Apartments
1,Sawtell,AU,82.00,clear sky,-30.38,153.10,Boambee Waters Caravan Park
0,Byron Bay,AU,86.00,scattered clouds,-28.65,153.62,Backpackers Inn on the Beach
3,Bundaberg,AU,93.20,scattered clouds,-24.85,152.35,Takalvan Motel
4,Yeppoon,AU,96.80,few clouds,-23.13,150.73,Villa Mar Colina
6,Mackay,AU,91.99,few clouds,-21.15,149.20,International Lodge Motel

In [34]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp}&deg F</dd>
</dl>
"""

In [35]:
# Store the DataFrame Row.
itinerary_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

In [36]:
# Add a pop-up marker for each city.
locations = itinerary_df[["Lat", "Lng"]]
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))